name: Packer CI Merged
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build AMI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm install
          npm install winston
          npm install node-statsd
          npm install hot-shots



      - name: Display .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_NAME=swaradb" >> .env
          echo "PORT=8080" >> .env
          cat .env

      - name: Configure MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          sudo systemctl start mysql
          sudo systemctl status mysql
          mysql -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" -e "CREATE DATABASE swaradb;"

      - name: Run Integration Tests
        run: npm test
 
      - name: Download webapp repository
        run: zip -r webapp.zip ./

      - name: Configure AWS Credentials
        run: |
              aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws configure set default.region us-east-1  # Replace with your desired AWS region
              aws configure set default.output json
              aws configure set profile.aws_cli_dev.aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws configure set profile.aws_cli_dev.aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Build AMI with Packer
        run: |
          packer init ami-packer.pkr.hcl
          packer fmt ami-packer.pkr.hcl
          packer build ami-packer.pkr.hcl
 
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_PROD_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_PROD_SECRET_KEY }}
          aws-region: us-east-1
      - name: Instance Refresh automation / Continuous Delivery
        run: |
          sudo apt-get install jq
          ASG_NAME=${{secrets.ASGNAME }}
          LAUNCH_CONFIG=${{secrets.LAUNCHTEMPLATENAME }}
          IMAGE=$(jq -r '.builds[-1].artifact_id' manifest.json | cut -d':' -f2)
          IMAGE_ID=$(jq -n \
          --arg img "$IMAGE" \
          '{"ImageId": $img}')
          aws ec2 create-launch-template-version \
          --launch-template-name "$LAUNCH_CONFIG" \
          --version-description updateAMI --source-version 1 \
          --launch-template-data="$IMAGE_ID"
          TEMPLATE_VERSION=$(aws ec2 describe-launch-template-versions --launch-template-name="$LAUNCH_CONFIG" \
          --filters="Name=is-default-version,Values=false" \
          --query 'sort_by(LaunchTemplateVersions, &CreateTime)[-1].[VersionNumber]' --output text)
          aws autoscaling update-auto-scaling-group --auto-scaling-group-name $ASG_NAME \
          --launch-template LAUNCHTEMPLATENAME="$LAUNCH_CONFIG",Version=$TEMPLATE_VERSION
          aws autoscaling start-instance-refresh \
          --auto-scaling-group-name $ASG_NAME --strategy Rolling
          printf "Instance refresh in progress"
          while true;
          do
            instance_refresh_status=$(aws autoscaling describe-instance-refreshes --auto-scaling-group-name $ASG_NAME \
            --query "InstanceRefreshes[0].Status" --output text)
            if [ "$instance_refresh_status" = "Successful" ]; then
              printf "\nInstance refresh successful!"
              break
           fi
           if [ "$instance_refresh_status" = "Cancelling" ] || [ "$instance_refresh_status" = "Cancelled" ] || [ "$instance_refresh_status" = "Failed" ]; then
             printf "\nInstance refresh failed!"
            exit 1
            fi
            echo -ne "."
            sleep 10
          done

        continue-on-error: true  # Ignore errors if the AMI ID is not found
