name: Packer CI

 

on:

  pull_request:

    branches:

      - main


jobs:

  nodejs:

    name: Node.js Workflow

    runs-on: ubuntu-latest

 

    steps:

      - name: Checkout code

        uses: actions/checkout@v2

 

      - name: Setup Node.js

        uses: actions/setup-node@v2

        with:

          node-version: 14

 

      - name: Install dependencies

        run: |

          npm install
          npm install winston
          npm install node-statsd
          npm install hot-shots

 

      - name: Display .env file

        run: |

          echo "DB_USER=${{ secrets.DB_USER }}" >> .env

          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

          echo "DB_NAME=swaradb" >> .env

          echo "PORT=8080" >> .env

          cat .env

 

      - name: Configure MySQL

        run: |

          sudo apt-get update

          sudo apt-get install -y curl

          sudo systemctl start mysql

          sudo systemctl status mysql

          mysql -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" -e "CREATE DATABASE swaradb;"

 

      - name: Run Tests

        run: npm test

 

  packer:

    name: Packer CI

    runs-on: ubuntu-latest

 

    steps:

      - name: Checkout

        uses: actions/checkout@v2

 

      - name: Download webapp repository

        run: 

          
          zip -r webapp.zip ./

          


           

      - name: Setup Packer

        uses: hashicorp/setup-packer@main

        with:

          packer_version: '1.8.6'

 

      - name: Initialize Packer

        run: packer init .

 

      - name: Run `packer fmt`

        run: |

          packer fmt -check ami-packer.pkr.hcl

 

      - name: Run `Build the webapp artifact`

        run: |

          packer fmt -check ami-packer.pkr.hcl

 

      - name: Run `packer validate`

        run: |

          packer validate ami-packer.pkr.hcl